#newPassword: Password must be at least 6 characters long
#resetPasswordLink: Token is required, it is the token that is already sent to the user

@baseUrl = http://localhost:8000/api

# @name resetPassword
POST {{baseUrl}}/reset-password  HTTP/1.1
content-type: application/json

{
    "newPassword": "aaaaa",
    "resetPasswordLink": "token from the email"
}
